#!/bin/bash

# Copyright (c) 2023 Robert LaRocca https://www.laroccx.com

# require root privileges
require_root_privileges() {
	if [[ "$(whoami)" != "root" ]]; then
		# logger -i "Error: gandi-livedns-update must be run as root!"
		echo "Error: gandi-livedns-update must be run as root!" 2>&1
		exit 2
	fi
}

require_root_privileges

install() {
	# install gandi-livedns-update command
	sudo cp -b -S .bak -v $PWD/gandi-livedns-update.sh \
		/usr/local/bin/gandi-livedns-update
	sudo chown root:root /usr/local/bin/gandi-livedns-update
	sudo chmod 0755 /usr/local/bin/gandi-livedns-update
}

symlink() {
	# create livedns symbolic link
	sudo ln -s /usr/local/bin/gandi-livedns-update \
		/usr/local/bin/livedns
}

install
symlink
