#!/bin/bash

# Copyright (c) 2021 Robert LaRocca https://www.laroccx.com

# require root privileges
require_root_privileges() {
	if [[ "$UID" != 0 ]]; then
		logger -i "Error: $(basename $0 .sh) must be run as root!"
		echo "Error: $(basename $0 .sh) must be run as root!"
		exit 1
	fi
};

require_root_privileges

main() {
	# install gandi-livedns-dynamic-updater command
	sudo cp -b -S .bak -v $PWD/gandi-livedns-dynamic-updater.sh \
		/usr/local/bin/gandi-livedns-dynamic-updater
	sudo chown root:root /usr/local/bin/gandi-livedns-dynamic-updater
	sudo chmod 0755 /usr/local/bin/gandi-livedns-dynamic-updater
};

main "$@"
